image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
   - npm install

test:
  stage: test
  variables:
    NODE_ENV: test
  services:
    - mongo:latest
  script: npm test
