image: node:latest

variables:
  NODE_ENV: test

stages:
  - test
  - deploy

test:
  stage: test
  services:
  - mongo:latest
  script:
    - npm install
    - npm test

all_tests:
  script:
    - npm install
    - npm start