apiVersion: v1
kind: Service
metadata:
   name: nodejs
   labels:
     run: nodejs
spec:
   ports:
   - port: 3000
     targetPort: 8080
     protocol: TCP
   type: NodePort
   selector:
     run: nodejs


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: nodejs
  spec:
    containers:
      - name: nodejs
        image: Dockerfile
        ports: containerPort: 8080