apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingress-service"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
spec:
  rules:
  - host: hello.back-eventine.pl # CHANGE ME!
  #to fix backend