apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: eventine
        name: web
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http-server